In [3]:
# import the module
import tweepy 
import json

# The Bearer Token
my_bearer_token = "AAAAAAAAAAAAAAAAAAAAAHLnbgEAAAAAvByqlm%2FvglMiJNBEwQDvt8TwV7c%3DWRIMVSLYba5wXl32PF1oFptYMj7JEUCSmuhbuy71Mk7chsI9H7"

# Client Creation 
client = tweepy.Client(bearer_token = my_bearer_token)

# screen name of the account to be fetched
#search_query = "#sarcasm -filters:retweets"

# query to search for tweets
query = "#sarcasm lang:en -is:retweet"

# your start and end time for fetching tweets
#start_time = "2022-04-16T09:43Z"
#end_time = "2022-04-16T12:43Z"

# get tweets from the API
tweets = client.search_recent_tweets(query=query,
                                     #start_time=start_time,
                                     #end_time=end_time,
                                     tweet_fields = ["created_at", "text", "source"],
                                     user_fields = ["name", "username", "location", "verified", "description"],
                                     max_results = 100,
                                     expansions='author_id'
                                    )


# tweet specific info
print(len(tweets.data))
# user specific info
print(len(tweets.includes["users"]))


# import the pandas library
import pandas as pd

# create a list of records
tweet_info_ls = []

# iterate over each tweet and corresponding user details
for tweet, user in zip(tweets.data, tweets.includes['users']):
    tweet_info = {
        'created_at': tweet.created_at,
        'text': tweet.text,
        #'source': tweet.source,
        #'name': user.name,
        #'username': user.username,
        #'location': user.location,
        #'verified': user.verified,
        'description': user.description
    }
    tweet_info_ls.append(tweet_info)
# create dataframe from the extracted records
tweets_df = pd.DataFrame(tweet_info_ls)
# display the dataframe
tweets_df.head()

100
86

,created_at,text,description
0,2022-04-23 11:04:33+00:00,It's said that #sarcasm is the lowest form of ...,
1,2022-04-23 11:03:42+00:00,I must weed out about 50 texts sounding like T...,There are millions of women in the world. And ...
2,2022-04-23 11:00:10+00:00,"Callon is back, #sarcasm intact. Check out the...",#IndieAuthor & #GeekGirl. Known for Dragonics ...
3,2022-04-23 10:40:01+00:00,Personality so inspiring that every girl I mee...,Follow: @diary_pen_and_coffee on Instagram!üî•Th...
4,2022-04-23 10:35:19+00:00,Why 50% valuation cut!? ‚ò†ü§∑‚Äç‚ôÇÔ∏è\n\nNifty is just...,Anticipate before other traders anticipate. üòâ

In [5]:
tweets_df.to_csv('raw_data.csv')